---
title: "First Knit"
author: "Leilani Guerrero"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I went to Pete Knight High School, I graduated in 2021. Math and English were about the same level of difficulty for me. I wasn't bad or extraordinarily good at either. I did the best in my science classes. I did the best in Biology.     

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
My computer is a windows computer. It a 9 out of 10 computer, in some instances I couldn't take test on it because it was too small. I rate myself a 8 out of 10 for computer geek. I couldn't figure anything out by myself but I can follow the directions really well and remember most of what I'm supposed to do. My internet connection is generally good, sometimes it crashes but it's always up working agai within a few minutes.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I don't care what my classmates or instructor calls me. Some people call me lani because it's easier than leilani  but either one is fine. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
i want to be a counselor for troubled children. i love to help people and I feel every child deserves a second chance. I am studying Sociology which is very interesting to me. I love to learn about people and why they behave the way they do. My current goal is to get a bachelors in Sociology but ultimently i want to get my Doctorate.    
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have been all over the U.S. but never been outside the country. However, I do want to be able to travel to every continent. Currently, Im saving up to go to Japan. I've never been in the military but almost everyone in my family has. If I were to get drafted, I would pray to go to the Air Force. It's clean, it's air conditioned, and comfortable.    
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
My counselor told me to take this class as a requirement. I did not know that 116 counts as taking stats in several transfer institutions, that's pretty cool. I need to keep an A in the class in order to higher my GPA.   
   
 






  




